config/routes.rb
Palette2::Application.routes.draw do

  root to: 'posts#index'

  get '/register', to: 'employees#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  resources :employees
  resources :posts do
    collection { post :sort }
  end
  resources :messages
  resources :recipes

end

app/models/employee.rb
class Employee < ActiveRecord::Base
  has_many :schedules
  has_many :posts
  validates :name, presence: true, uniqueness: true
  validates :password, presence: true, on: :create
  has_secure_password validations: false
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :employee

  validates :note, :user, presence: true
  validates :user, length: {maximum: 10}
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :employee
  acts_as_list

  validates :chef1, :chef2, :chef3 , presence: true
  validates :day, presence: true, length: {maximum: 3}

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base

end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
  belongs_to :employee
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_employee, :logged_in?

  def current_employee
    @current_employee ||= Employee.find(session[:employee_id]) if session[:employee_id]
  end

  def logged_in?
    !!current_employee
  end

  def require_employee
    if !logged_in?
      flash[:error] = 'You need to log in '
      redirect_to root_path
    end
  end

end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:edit, :update, :show, :destroy]

  def index
    @employees = Employee.order(:updated_at)
  end

  def new
    @employee = Employee.new
  end

  def create
    @employee = Employee.new(employee_params)

    if @employee.save
      session[:employee_id] = @employee.id
      flash[:notice] = "You are registered"
      redirect_to root_path
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
     if @employee.update(employee_params)
      flash[:notice] = "This one has been updated"
      redirect_to posts_path(@posts)
    else
      render :edit
    end
  end


  private

  def employee_params
    params.require(:employee).permit(:name, :password)
  end

  def set_employee
    @employee = Employee.find(params[:id])
  end


end

app/controllers/messages_controlle.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:edit, :update, :show]

  def index
    @messages = Message.all
  end

  def new
    @message = Message.new
  end

  def create
    @message = Message.new(message_params)

    if @message.save
      flash[:notice] = "You have posted a message"
      redirect_to messages_path
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @message.update
      flash[:notice] = "You have updated your message"
      redirect_to messages_path(@messages)
    else
      render :edit
    end
  end



  private

  def message_params
    params.require(:message).permit(:note)
  end

  def set_message
    @message = Message.find(params[:id])
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:edit, :update, :show]

  def index
    @messages = Message.order(:updated_at).reverse
  end

  def new
    @message = Message.new
  end

  def create
    @message = Message.new(message_params)

    if @message.save
      flash[:notice] = "You have posted a message"
      redirect_to posts_path
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @message.update(message_params)
      flash[:notice] = "You have updated your message"
      redirect_to posts_path(@posts)
    else
      render :edit
    end
  end



  private

  def message_params
    params.require(:message).permit(:note, :user, :created_at, :updated_at)
  end

  def set_message
    @message = Message.find(params[:id])
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:update, :show]

  def index
    @posts = Post.order("position")
    @messages = Message.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)

    if @post.save
      flash[:notice] = "A new post has been created"
      redirect_to posts_path
    else
      render :new
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    if @post.update(post_params)
      flash[:notice] = "The schedule was updated"
      redirect_to posts_path(@post)
    else
      render :edit
    end
  end


  def sort
    params[:post].each_with_index do |id, index|
    Post.update_all({position: index+1}, {id: id})
  end
    render nothing: true
  end

  private

  def post_params
    params.require(:post).permit(:day, :shift, :shift2, :chef1, :chef2, :chef3, :chef4, :chef5, :chef6, :chef7, :chef8, :chef9, :chef10, :title, :description)
  end

  def set_post
    @post = Post.find(params[:id])
  end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

def index
  @recipes = Recipe.all
end

def new
  @recipe = Recipe.new
end

def create
  @recipe = Recipe.new
end

end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :set_schedule, only: [:show, :edit, :update]

  def index
    @schedules = Schedule.all
    @employees = Employee.all
  end

  def new
    @schedule = Schedule.new
  end

  def create
    @schedule = Schedule.new(schedule_params)

    if @schedule.save
      flash[:notice] = "You have added a shift"
      redirect_to schedules_path
    else
      render :new
    end
  end

  def show

  end

  def edit
  end

  def update

  end

  private

  def schedule_params
    params.require(:schedule).permit(:day, :shift)
  end

  def set_schedule
    @schedule = Schedule.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create
    employee = Employee.where(name: params[:name]).first
    if employee && employee.authenticate(params[:password])
      session[:employee_id] = employee.id
      flash[:notice] = "Welcome aboard"
      redirect_to root_path
    else
      flash[:error] = "There is something wrong, please fix"
      redirect_to login_path
    end
  end

  def destroy
    session[:employee_id] = nil
    flash[:notice] = "You are out!!!!"
    redirect_to root_path
  end
end

app/views/employees/_form.html.erb
<div class='well'>
  <%= form_for @employee do |f| %>

    <div class='control-group'>
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
    <div class='control-group'>
      <%= f.label :password %>
      <%= f.password_field :password %>
    </div>
    <%= f.submit @employee.new_record? ? "Register" : "Update", class: 'btn btn-success' %>
  <% end %>
</div>

app/views/employees/edit.html.erb
<h4>Update Profile</h4>
<%= render 'form' %>

app/views/employees/index.html.erb
<h3>Rollers</h3>

<div class="row">
  <ul id="employees">
  <% @employees.each do |employee| %>
  <div class="span1 well">
    <%= content_tag_for :dt, employee do %>
      <%= employee.name %>
      <%= link_to "Show", employee_path(employee) %>
    <% end %>
  </div>
  <% end %>
  </ul>
</div>

<div class="span1 well">
<small><%= link_to "Add Chef", new_employee_path %></small>
</div>

app/views/employees/new.html.erb
<h3>Register</h3>
<%= render 'form' %>

app/views/employees/show.html.erb
<h3>Chef's name : </h3>

<h4><%= @employee.name %></h4>
<h5><%= @employee.title %></h5>
<p><%= @employee.description %></p>

<h4><%= link_to "Edit", edit_employee_path %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<ul class="nav">
  <li>
    <%= link_to "B-Side ITR", root_path, :class => 'brand' %>
  </li>

  <% if logged_in? %>
    <li>
        <%= link_to "Logout", logout_path %>
    </li>
  <% else %>
    <li>
    <%= link_to "Login", login_path %>
  </li>
  <% end %>
  <li>
    <%= link_to "Message", new_message_path %>
  </li>
  <li>
    <%= link_to "Recipes", new_recipe_path %>
  </li>

</ul>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Project Palette</title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header>
      <div class="navbar navbar-inverse">
        <div class="navbar-inner">
          <div class="container">
            <%= render 'layouts/navigation' %>
          </div>
        </div>
      </div>
    </header>
    <div id="main" role="main">
      <div class="container">
         <div class="row">
          <div class="span12">
            <%= render 'layouts/messages' %>
            <%= yield %>
          </div>
        </div>
        <footer>
        </footer>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/messages/_form.html.erb
<body>
  <div class="well">
    <h4>Leave your name and message here</h4>
    <%= form_for @message do |f| %>
      <tr>
        <div class='control-group'>
          <%= f.label :user %>
          <%= f.text_field :user%>
        </div>
        <div class='control-group'>
          <%= f.label :note %>
          <%= f.text_area :note, rows: 8 %>
        </div>

          <%= f.submit @message.new_record? ? "Post It" : "Update Note", class: 'btn btn-success' %>
    <% end %>
    </div>
  </div>
</body>

app/views/messages/edit.html.erb
<%= render 'form' %>

app/views/messages/index.html.erb
<h3>Messages</h3>

<div class="well">
  <% @messages.each do |message| %>
    <%= message.note %>
  <% end %>
  <br/>
  <%= link_to "Edit", edit_message_path %>
</div>

app/views/messages/new.html.erb
<body>
  <div class='well'>
    <%= form_for @message do |f| %>
      <tr>
        <div class='control-group'>
          <%= f.label :note %>
          <%= f.text_area :note, rows: 8 %>
        </div>

      <%= f.submit @message.new_record? ? "Post It" : "Update Note", class: 'btn btn-success' %>
    <% end %>
  </div>
</body>

app/views/posts/_form.html.erb
<body>
   <h4><font color="crimson">Title is for dates and only fill it once</h4><font>
  <div class='well'>
    <%= form_for @post do |f| %>
      <tr>
        <div class='control-group'>
          <%= f.label :title %>
          <%= f.text_field :title %>
        </div>
        <div class='control-group'>
          <%= f.label :day %>
          <%= f.text_field :day %>
        </div>
        <div class='control-group'>
          <%= f.label :shift %>
          <%= f.text_field :shift %>
        </div>
        <div class='control-group'>
          <%= f.label :chef1 %>
          <%= f.text_field :chef1 %>
        </div>
        <div class='control-group'>
          <%= f.label :chef2 %>
          <%= f.text_field :chef2 %>
        </div>
        <div class='control-group'>
          <%= f.label :chef3 %>
          <%= f.text_field :chef3 %>
        </div>
        <div class='control-group'>
          <%= f.label :chef4 %>
          <%= f.text_field :chef4 %>
        </div>
        <div class='control-group'>
          <%= f.label :chef5 %>
          <%= f.text_field :chef5 %>
        </div>
        <div class='control-group'>
          <%= f.label :shift2 %>
          <%= f.text_field :shift2 %>
        </div>
        <div class='control-group'>
          <%= f.label :chef6 %>
          <%= f.text_field :chef6 %>
        </div>
        <div class='control-group'>
          <%= f.label :chef7 %>
          <%= f.text_field :chef7 %>
        </div>
        <div class='control-group'>
          <%= f.label :chef8 %>
          <%= f.text_field :chef8 %>
        </div>
        <div class='control-group'>
          <%= f.label :chef9 %>
          <%= f.text_field :chef9 %>
        </div>
        <div class='control-group'>
          <%= f.label :chef10 %>
          <%= f.text_field :chef10 %>
        </div>
        <div class='control-group'>
        <%= f.label :description %>
        <%= f.text_area :description, rows: 4 %>
        </div>
      </tr>
      <%= f.submit @post.new_record? ? "Create Shift" : "Update Shift", class: 'btn btn-success' %>
    <% end %>
  </div>
</body>

app/views/posts/edit.html.erb
<% if logged_in? %>
  <%= render 'form' %>
<% end %>

app/views/posts/index.html.erb
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="assets/css/bootstrap-responsive.css" rel="stylesheet">
</head>

<body>
  <div class="well">
    <% @posts.each do |post| %>
    <center><h3><font color="steelblue"><%= post.title %></font></h3></center>
    <% end %>
  </div>

  <div class="row">
    <ul id="posts" data-update-url="<%= sort_posts_url %>">

    <div class="rocks">
    <% @posts.each do |post| %>
    <div class="span1 well">
      <%= content_tag_for :dt, post do %>
          <h4><font color="steelblue"><%= post.day %></font></h4>
          <h5><font color="turquoise"><%= post.shift %></font></h5>
          <h6><%= post.chef1 %></h6>
          <h6><%= post.chef2 %></h6>
          <h6><%= post.chef3 %></h6>
          <h6><%= post.chef4 %></h6>
          <h6><%= post.chef5 %></h6>
          <h5><font color="turquoise"><%= post.shift2 %></font></h5>
          <h6><%= post.chef6 %></h6>
          <h6><%= post.chef7 %></h6>
          <h6><%= post.chef8 %></h6>
          <h6><%= post.chef9 %></h6>
          <h6><%= post.chef10 %></h6>
          <h6><font color="red"><%= post.description %></font></h6>
          <% if logged_in? %>
            <h6><%= link_to "Edit", edit_post_path(post) %></h6>
          <% end %>
      <% end %>
    </div>
    <% end %>
    </div>
    </ul>
  </div>


<h4>Messages / Requests</h4>

<% @messages.each do |message| %>
  <div class="span3 well">
    <font color="olive"><%= message.user %></font>
    <br/>
    <%= message.note %>
    <br/>
    <% if logged_in? %>
      <small><%= link_to "Edit", edit_message_path(message) %></small>
    <% end %>
    <br/>
    <small>Posted on <%= message.created_at %></small>
  </div>
  <% end %>
</body>
<br/>

app/views/posts/new.html.erb
<%= render 'form' %>

app/views/recipes/new.html.erb
<body>
  <div class="well">
    <h4>Write your recipe:</h4>
    <%= form_for @recipe do |f| %>
      <tr>
        <div class='control-group'>
          <%= f.label :recipe %>
          <%= f.text_area :recipe, rows: 8 %>
        </div>


          <%= f.submit @recipe.new_record? ? "Post It" : "Update Note", class: 'btn btn-success' %>
    <% end %>
    </div>
  </div>
</body>

app/views/schedules/etc.html.erb
<div class="well">
  <div class="table-responsive">
    <table class="table">
      <tr>
        <th>Name</th>
        <th>Sunday</th>
        <th>Monday</th>
        <th>Tuesday</th>
        <th>Wednesday</th>
        <th>Thursday</th>
        <th>Friday</th>
        <th>Saturday</th>
      </tr>
      <tr>
        <th>
          <% @employees.each do |employee| %>
          <dt>
            <dl><%= employee.name %></dl>
            <% end %>
          </dt>
        </th>
      </tr>
    </table>
  </div>
</div>

app/views/schedules/index.html.erb
<h3>Shifts</h3>

<div class="well">
  <div class="table-responsive">
    <table class="table">
      <ul id="days">
        <tr>
          <th>Name</th>
          <th>Sunday</th>
          <th>Monday</th>
          <th>Tuesday</th>
          <th>Wednesday</th>
          <th>Thursday</th>
          <th>Friday</th>
          <th>Saturday</th>
        </tr>
      </ul>
      <tr>
        <th>
          <% @employees.each do |employee| %>
          <dt>
            <dl><%= employee.name %></dl>
            <% end %>
          </dt>
        </th>
      </tr>
    </table>
  </div>
</div>
</br>

<div class="row">
  <ul id="schedules">
  <% @schedules.each do |schedule| %>
    <div class="span1 well">
      <%= content_tag_for :dt, schedule do %>
        <%= schedule.shift %>
      <% end %>
    </div>
  <% end %>
  </ul>
</div>

app/views/schedules/new.html.erb
<div class='well'>
  <%= form_for @schedule do |f| %>

    <div class='control-group'>
      <%= f.label :shift %>
      <%= f.text_field :shift %>
    </div>
    <%= f.submit @schedule.new_record? ? "Add Shift" : "Update", class: 'btn btn-success' %>
  <% end %>
</div>